"""Edir pitch module

Revision ID: 773a5433e67b
Revises: f1acbf1c4344
Create Date: 2019-05-28 18:07:33.524159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773a5433e67b'
down_revision = 'f1acbf1c4344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('pitch', sa.Column('upvote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'upvote')
    op.drop_column('pitch', 'downvote')
    # ### end Alembic commands ###
