"""edit arg in pitch model

Revision ID: 95753fe9133b
Revises: ac1d49629eba
Create Date: 2019-05-28 19:17:36.548588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95753fe9133b'
down_revision = 'ac1d49629eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('pitch_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'pitch_id')
    # ### end Alembic commands ###
