"""edit arg in pitch model

Revision ID: ac1d49629eba
Revises: 773a5433e67b
Create Date: 2019-05-28 19:08:49.291974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1d49629eba'
down_revision = '773a5433e67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'vote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('vote', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
